#!/usr/bin/env bash

# Update package index
sudo apt-get update
# Install nginx
sudo apt-get -y install nginx
# Replace the default index.html with one that says "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
# Reload nginx to pick up the new index.html file
sudo service nginx reload
# Although you've stated not to use systemctl, it's worth mentioning that
# if nginx is not active (running), you should start it using:
# sudo systemctl start nginx
# In environments where systemctl is not available, use:
sudo service nginx start
